name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics(left)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}
          filename: metrics_left.svg
          base: header
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_categories: programming
          plugin_languages_recent_categories: markup, programming, data
          plugin_languages_recent_load: 500
          plugin_languages_recent_days: 7
          commits_authoring: hiro527.dev@gmail.com
      - name: Metrics(right)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}
          filename: metrics_right.svg
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_achievements_ignored: octonaut
          plugin_achievements_limit: 0
          plugin_achievements_display: compact